### PR TITLE
Adopt `ruff`, `black`, fix various issues

### PR DESCRIPTION
**Pull request by jtpio**
Build on top of https://github.com/jupyterlite/xeus-python-kernel/pull/168

This will help catch potential issues:

- [x] Adopt `ruff`
- [x] Adopt `black`
- [x] Lint pass
- [x] Fix some typing issues
- [x] Run linting on CI

### CODE REVIEW

**Comment by jtpio** [comment]
Will wait for https://github.com/jupyterlite/xeus-python-kernel/pull/168 to get in first.

**Comment by martinRenou** [comment]
@jtpio FYI I'm rebasing this

**Review by martinRenou — APPROVED** [review]
Thank you! Let's merge when green

**Comment by martinRenou** [comment]
meeseeksdev backport to 0.x

**Pull request merged**
