### PR TITLE
Add docs

### PR DESCRIPTION
**Pull request by martinRenou**

### CODE REVIEW

**Comment by martinRenou** [comment]
Docker is not available on readthedocs so we won't be able to do that. We'll need to have the docs use a released version of xeus-python-kernel.

**Comment by jtpio** [comment]
CI failure looks relevant, although the dependency on `@jupyterlab/builder` seems to be correct at first glance.

**Comment by jtpio** [comment]
Seems to be failing on `main` as well.

**Comment by martinRenou** [comment]
Yes, I was merging knowing it was relevant (but not relevant to the docs). Just pushed an hopeful fix here https://github.com/jupyterlite/xeus-python-kernel/pull/5

**Pull request merged**
