### PR TITLE
Update xeus-python in docs

### PR DESCRIPTION
**Pull request by martinRenou**

### CODE REVIEW

**Comment by jtpio** [comment]
Wondering if the docs should build the kernel from source maybe?

This could allow for having RTD previews on PRs?

**Comment by martinRenou** [comment]
Yeah I've been wanting to do this.

The issue is that Docker is not available on RTD, so we would need to get rid of the Docker setup in order to make it possible, which is feasible.

**Comment by jtpio** [comment]
Ah right.

So probably the xeus refactor (https://xeus.readthedocs.io/en/latest/dev.html) will make it possible to not have to use `docker` anymore for building xeus python.

**Comment by martinRenou** [comment]
I don't think that matters much. The Dockerfile does not compile xeus-python at all, it only installs it from emscripten-forge using micromamba.

So the impact of removing the Dockerfile would be that the dev env should have micromamba available. We can also probably allow using conda or mamba instead of micromamba, but that would complicate things a bit for the build workflow.

**Pull request merged**
