### PR TITLE
Add Matplotlib to the env

### PR DESCRIPTION
**Pull request by martinRenou**
cc. @DerThorsten @jtpio

Adding Matplotlib to the env, this way people can use it.

This is probably temporary, until we have a way to install packages with mamba.

### CODE REVIEW

**Comment by martinRenou** [comment]
Making this a draft for now. I am testing it locally and will come back with a screenshot.

**Comment by martinRenou** [comment]
🚀 🚀 🚀 🚀 

xeus-python-matplotlib

**Comment by martinRenou** [comment]
The dist is now 64Mb...

**Comment by martinRenou** [comment]
> The dist is now 64Mb...

Well pyodide is 176MB so let's go ahead with this PR for now.

**Comment by DerThorsten** [comment]
@martinRenou feel free to press the merge button

**Comment by jtpio** [comment]
Indeed the size is fine for now.

Thanks!

**Pull request merged**
