### PR TITLE
Update to `jupyterlite==0.1.0b17` in the docs

### PR DESCRIPTION
**Pull request by jtpio**
Update to the latest JupyterLite release in the documentation: https://github.com/jupyterlite/jupyterlite/releases/tag/v0.1.0b17

### CODE REVIEW

**Comment by martinRenou** [comment]
Thanks! Could you please rebase your branch so we can test it on ReadTheDocs from the PR?

**Comment by jtpio** [comment]
I just enabled the button to easily be able to update the branch from the GitHub UI: 

image

**Comment by martinRenou** [comment]
Thanks! I did not know it had to be enabled manually

**Comment by jtpio** [comment]
Yep it's super useful. It's in "Settings > Pull Requests".

**Review by martinRenou — APPROVED** [review]
Thanks!

**Pull request merged**
